"""Validation Against Mantid
===========================

This tutorial demonstrates the validation of `abinslib` calculations by comparing 
them directly against output from the Mantid `abins` algorithm.
"""

# %%
# Setup and Data Fetching
# -----------------------
# First, we fetch the necessary reference data using our Pooch registry. This includes
# the raw phonon modes and the corresponding JSON spectra generated by Mantid.

from abinslib.data import get_data, get_validation_data
from euphonic import QpointPhononModes, Quantity, Spectrum1D
import matplotlib.pyplot as plt
import numpy as np

from abinslib.almost_isotropic_incoherent import (
    calculate_almost_isotropic_incoherent_spectra,
    mantid_like_combination_spectra,
)
from abinslib.isotropic_incoherent import q_scaling_isotropic_incoherent_spectra
from abinslib.displacements import Displacements
from abinslib.util import apply_weights, calculate_indirect_q2
from euphonic.plot import plot_1d_to_axis

# Fetch base inputs
castep_file = get_validation_data("ethanol_qpoint_phonon_modes.json")
modes = QpointPhononModes.from_json_file(castep_file)

# Fetch Mantid references
mantid_iso_file = get_validation_data("ethanol_mantid_isotropic_fundamentals.json")
mantid_almost_iso_file = get_validation_data(
    "ethanol_mantid_almost_isotropic_fundamentals.json"
)
mantid_second_order_file = get_validation_data("ethanol_mantid_second_order.json")

mantid_iso = Spectrum1D.from_json_file(mantid_iso_file)
mantid_almost_iso = Spectrum1D.from_json_file(mantid_almost_iso_file)
mantid_second_order = Spectrum1D.from_json_file(mantid_second_order_file)

# Extract shared parameters from Mantid output
temperature = Quantity(float(mantid_iso.metadata["temperature"]), "kelvin")
bins = mantid_iso.get_bin_edges(restrict_range=False)
width = Quantity(1, "meV")

# Prepare displacement data
displacements = Displacements.from_modes(modes, temperature=temperature)
dw = displacements.to_atomic_displacements()

# Common kinematic parameters for TOSCA (134.99 degrees, Ef = 32 cm^-1)
angle = 134.98885653282196 * np.pi / 180
final_energy = Quantity(32.0, "cm_1").to("hartree")


def format_validation_plot(ax, title, xlim, linear=False):
    """Helper to format the matplotlib axes consistently."""
    ax.legend()
    ax.set_title(title + f"\n{width:~P} broadening")
    ax.set_xlim(0, xlim)
    ax.set_xlabel("Energy transfer / meV")
    ax.set_ylabel("$S(\omega)$ / barn meV$^{-1}$")
    if not linear:
        ax.set_yscale("log")
    plt.tight_layout()


# %%
# Isotropic Fundamentals
# ----------------------
# For the fully isotropic fundamental spectrum, the Mantid-Abins approximation 
# uses the bin centres to compute the scalar $Q^2$ array used for scaling.

q2_iso = calculate_indirect_q2(
    mantid_iso.get_bin_centres(),
    angle=angle,
    final_energy=final_energy,
)

spectra_iso = q_scaling_isotropic_incoherent_spectra(
    modes, displacements, dw, q2_iso, bins
)
spectra_iso = apply_weights(spectra_iso)
abinslib_iso = spectra_iso.sum()

# Plot comparison
fig, ax = plt.subplots()
plot_1d_to_axis(
    abinslib_iso.broaden(width), ax, label="q_scaling_isotropic_incoherent_spectra"
)
plot_1d_to_axis(
    mantid_iso.broaden(width),
    ax,
    linestyle="--",
    label="Mantid-Abins isotropic fundamentals",
)

format_validation_plot(
    ax,
    "Ethanol isotropic fundamentals:\n$134.99^\circ E_f = 32 \mathrm{cm}^{-1}$",
    xlim=200,
)

# %%
# Almost-Isotropic Fundamentals
# -----------------------------
# For the almost-isotropic fundamentals, the $Q^2$ scaling relies on the 
# individual mode frequencies rather than the binned energy transfer centres.

q2_almost_iso = calculate_indirect_q2(
    modes.frequencies,
    angle=angle,
    final_energy=final_energy,
)

spectra_almost_iso = calculate_almost_isotropic_incoherent_spectra(
    modes, displacements, dw, q2_almost_iso, bins
)
spectra_almost_iso = apply_weights(spectra_almost_iso)
abinslib_almost_iso = spectra_almost_iso.sum()

# Plot comparison
fig, ax = plt.subplots()
plot_1d_to_axis(
    abinslib_almost_iso.broaden(width),
    ax,
    label="calculate_almost_isotropic_incoherent_spectra",
)
plot_1d_to_axis(
    mantid_almost_iso.broaden(width),
    ax,
    linestyle="--",
    label="Mantid-Abins almost-isotropic fundamentals",
)

format_validation_plot(
    ax,
    "Ethanol almost-isotropic fundamentals:\n$134.99^\circ E_f = 32 \mathrm{cm}^{-1}$",
    xlim=200,
)


# %%
# Second-Order Spectra
# --------------------
# Second-order combination band spectra using the Mantid-like approximation. 
# Notice that the `mantid_like_combination_spectra` applies its own specific 
# cross-section weighting internally due to the multi-phonon mode combinations.

q2_second_order = calculate_indirect_q2(
    mantid_second_order.get_bin_centres(),
    angle=angle,
    final_energy=final_energy,
)

spectra_second_order = mantid_like_combination_spectra(
    modes, displacements, dw, q2_second_order, bins
)
spectra_second_order = apply_weights(spectra_second_order)
abinslib_second_order = spectra_second_order.sum()

# Plot comparison
fig, ax = plt.subplots()
plot_1d_to_axis(
    abinslib_second_order.broaden(width),
    ax,
    label="mantid_like_combination_spectra",
)
plot_1d_to_axis(
    mantid_second_order.broaden(width),
    ax,
    linestyle="--",
    label="Mantid-Abins almost-isotropic second-order",
)

format_validation_plot(
    ax,
    "Ethanol second order:\n$134.99^\circ E_f = 32 \mathrm{cm}^{-1}$",
    xlim=420,
)
