configfile: "config/config.yml"

rule all:
    input:
        "results/ethanol_mantid_isotropic_fundamentals.json",
        "results/ethanol_mantid_almost_isotropic_fundamentals.json",
        "results/ethanol_mantid_second_order.json",

rule write_isotropic_fundamentals_mantid:
    input:
        "data/{label}_qpoint_phonon_modes.json",
    output:
        "results/{label}_mantid_isotropic_fundamentals.json",
    params:
        raw=True,
        isotropic=True,
        abins_kwargs=config["abins_kwargs"],
    script:
        "scripts/write_mantid_fundamentals.py"

rule write_almost_isotropic_fundamentals_mantid:
    input:
        "data/{label}_qpoint_phonon_modes.json",
    output:
        "results/{label}_mantid_almost_isotropic_fundamentals.json",
    params:
        raw=True,
        isotropic=False,
        abins_kwargs=config["abins_kwargs"],
    script:
        "scripts/write_mantid_fundamentals.py"

rule write_second_order_mantid:
   input:
       "data/{label}_qpoint_phonon_modes.json",
   output:
       "results/{label}_mantid_second_order.json",
   params:
       raw=True,
       abins_kwargs=config["abins_kwargs"]
   script:
       "scripts/write_mantid_second_order.py"
