[workspace]
authors = ["Adam J. Jackson <a.j.jackson@physics.org>"]
channels = ["conda-forge", "mantid", "bioconda", "nodefaults"]
name = "validation-data"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
generate = "snakemake --cores 1"
# Zip up the generated json files and inputs for reference archive
archive = "zip -j validation-data-v1.zip results/*_mantid_*.json data/*.json"
# Generate sha256 hashes of results for the Pooch registry
hashes = "python scripts/hash_results.py"
# Check newly generated sha256 hashes against reference registry
check-hashes = "python scripts/hash_results.py | python scripts/check_hashes.py -"
# Run tests for dev validation scripts
test = "pytest tests"

[dependencies]
snakemake = "~=9.16.3"
mantid = "~=6.15.0"
pytest = ">=8.0"
