name: Generate Validation Data

on:
  workflow_dispatch:

jobs:
  validate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.73.0
          manifest-path: dev/validation/pixi.toml

      - name: Generate Mantid JSON Data
        working-directory: dev/validation
        run: pixi run generate

      - name: Check against Reference Registry
        working-directory: dev/validation
        run: |
          pixi run hashes
          pixi run check-hashes

      - name: Archive JSON Data
        if: always()
        working-directory: dev/validation
        run: pixi run archive

      - name: Upload Validation Data Archive
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: validation-data-v1
          path: dev/validation/validation-data-v1.zip
          retention-days: 14
